/* A dependency-free ecommerce API. Start with: node server.js */
const http = require('node:http');
const { randomUUID, randomBytes, scryptSync, timingSafeEqual } = require('node:crypto');
const { existsSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');

const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = join(__dirname, '.data');
const DATA_FILE = join(DATA_DIR, 'store.json');
const now = () => new Date().toISOString();
const id = () => randomUUID();
const money = (n) => Number.isInteger(n) && n >= 0;
const safeUser = ({ passwordHash, ...user }) => user;
const hashPassword = (password, salt = randomBytes(16).toString('hex')) => `${salt}:${scryptSync(password, salt, 64).toString('hex')}`;
const verifyPassword = (password, saved) => { const [salt, expected] = saved.split(':'); const actual = scryptSync(password, salt, 64).toString('hex'); return timingSafeEqual(Buffer.from(expected, 'hex'), Buffer.from(actual, 'hex')); };
const slugify = (s) => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

function seed() {
  const category = { id: id(), name: 'Pantry', slug: 'pantry' };
  const products = [
    ['Organic Oat Milk', 'Creamy, shelf-stable oat milk.', 499, 24],
    ['Sea Salt Crackers', 'Crisp crackers made with simple ingredients.', 349, 40],
    ['Sparkling Water', 'Naturally flavored, 8-pack.', 699, 18]
  ].map(([name, description, priceCents, quantity]) => { const productId = id(); return { product: { id: productId, categoryId: category.id, name, slug: slugify(name), description, priceCents, active: true, createdAt: now() }, inventory: { productId, quantity, updatedAt: now() } }; });
  return { users: [], sessions: [], categories: [category], products: products.map(x => x.product), inventory: products.map(x => x.inventory), addresses: [], carts: [], cartItems: [], orders: [], orderItems: [], payments: [] };
}
function load() { if (!existsSync(DATA_FILE)) return seed(); try { return JSON.parse(readFileSync(DATA_FILE, 'utf8')); } catch { return seed(); } }
let db = load();
function save() { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(DATA_FILE, JSON.stringify(db, null, 2), 'utf8'); }
function productView(product) { const stock = db.inventory.find(x => x.productId === product.id)?.quantity || 0; const category = db.categories.find(x => x.id === product.categoryId); return { ...product, category: category ? { id: category.id, name: category.name, slug: category.slug } : null, inventory: stock }; }
function cartView(userId) { const cart = db.carts.find(x => x.userId === userId); const items = (cart ? db.cartItems.filter(x => x.cartId === cart.id) : []).map(item => { const product = db.products.find(x => x.id === item.productId); return { id: item.id, product: productView(product), quantity: item.quantity, lineTotalCents: product.priceCents * item.quantity }; }); const subtotalCents = items.reduce((total, x) => total + x.lineTotalCents, 0); return { id: cart?.id || null, items, subtotalCents, currency: 'USD' }; }
function body(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > 1_000_000) req.destroy(); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(Object.assign(new Error('Body must be valid JSON'), { status: 400 })); } }); req.on('error', reject); }); }
function respond(res, status, value) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' }); res.end(JSON.stringify(value)); }
function fail(status, message, code = 'REQUEST_ERROR') { const error = new Error(message); error.status = status; error.code = code; throw error; }
function validString(v, label, min = 1, max = 300) { if (typeof v !== 'string' || v.trim().length < min || v.trim().length > max) fail(422, `${label} must be ${min}-${max} characters`, 'VALIDATION_ERROR'); return v.trim(); }
function auth(req, admin = false) { const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, ''); const session = db.sessions.find(x => x.token === token && x.expiresAt > now()); if (!session) fail(401, 'Authentication required', 'UNAUTHORIZED'); const user = db.users.find(x => x.id === session.userId); if (!user) fail(401, 'Authentication required', 'UNAUTHORIZED'); if (admin && user.role !== 'admin') fail(403, 'Admin access required', 'FORBIDDEN'); return user; }
function createToken(userId) { const token = randomBytes(32).toString('base64url'); db.sessions.push({ token, userId, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString() }); return token; }
function address(data) { const fields = ['recipient', 'line1', 'city', 'state', 'postalCode', 'country']; const out = {}; for (const field of fields) out[field] = validString(data[field], field, 1, field === 'country' ? 2 : 120); out.line2 = data.line2 ? validString(data.line2, 'line2', 1, 120) : ''; return out; }
function orderView(order) { return { ...order, items: db.orderItems.filter(x => x.orderId === order.id), payment: db.payments.find(x => x.orderId === order.id) || null }; }

async function handler(req, res) {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); const path = url.pathname; const method = req.method;
  if (method === 'OPTIONS') { res.writeHead(204, { 'access-control-allow-origin': '*', 'access-control-allow-headers': 'authorization, content-type, idempotency-key', 'access-control-allow-methods': 'GET,POST,PATCH,DELETE,OPTIONS' }); return res.end(); }
  try {
    if (method === 'GET' && path === '/api/health') return respond(res, 200, { ok: true });
    if (method === 'POST' && path === '/api/auth/register') { const d = await body(req); const email = validString(d.email, 'email', 3, 254).toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) fail(422, 'email is invalid', 'VALIDATION_ERROR'); const password = validString(d.password, 'password', 12, 200); if (db.users.some(x => x.email === email)) fail(409, 'Email already registered', 'CONFLICT'); const user = { id: id(), email, name: validString(d.name, 'name', 1, 100), passwordHash: hashPassword(password), role: 'customer', createdAt: now() }; db.users.push(user); const token = createToken(user.id); save(); return respond(res, 201, { user: safeUser(user), token }); }
    if (method === 'POST' && path === '/api/auth/login') { const d = await body(req); const user = db.users.find(x => x.email === String(d.email || '').toLowerCase()); if (!user || !verifyPassword(String(d.password || ''), user.passwordHash)) fail(401, 'Invalid email or password', 'INVALID_CREDENTIALS'); const token = createToken(user.id); save(); return respond(res, 200, { user: safeUser(user), token }); }
    if (method === 'POST' && path === '/api/auth/logout') { const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, ''); db.sessions = db.sessions.filter(x => x.token !== token); save(); return respond(res, 204, {}); }
    if (method === 'GET' && path === '/api/me') return respond(res, 200, { user: safeUser(auth(req)) });
    if (method === 'GET' && path === '/api/categories') return respond(res, 200, { categories: db.categories });
    if (method === 'GET' && path === '/api/products') { let products = db.products.filter(x => x.active); const q = url.searchParams.get('q')?.toLowerCase(); const category = url.searchParams.get('category'); if (q) products = products.filter(x => `${x.name} ${x.description}`.toLowerCase().includes(q)); if (category) products = products.filter(x => x.categoryId === category || db.categories.find(c => c.id === x.categoryId)?.slug === category); return respond(res, 200, { products: products.map(productView) }); }
    if (method === 'GET' && /^\/api\/products\/[^/]+$/.test(path)) { const key = decodeURIComponent(path.split('/').pop()); const product = db.products.find(x => x.id === key || x.slug === key); if (!product || !product.active) fail(404, 'Product not found', 'NOT_FOUND'); return respond(res, 200, { product: productView(product) }); }
    if (method === 'GET' && path === '/api/addresses') { const user = auth(req); return respond(res, 200, { addresses: db.addresses.filter(x => x.userId === user.id) }); }
    if (method === 'POST' && path === '/api/addresses') { const user = auth(req); const entry = { id: id(), userId: user.id, ...address(await body(req)) }; db.addresses.push(entry); save(); return respond(res, 201, { address: entry }); }
    if (method === 'GET' && path === '/api/cart') { const user = auth(req); return respond(res, 200, { cart: cartView(user.id) }); }
    if (method === 'POST' && path === '/api/cart/items') { const user = auth(req); const d = await body(req); const product = db.products.find(x => x.id === d.productId && x.active); if (!product) fail(404, 'Product not found', 'NOT_FOUND'); if (!Number.isInteger(d.quantity) || d.quantity < 1 || d.quantity > 99) fail(422, 'quantity must be an integer from 1 to 99', 'VALIDATION_ERROR'); const stock = db.inventory.find(x => x.productId === product.id).quantity; if (d.quantity > stock) fail(409, 'Insufficient inventory', 'INSUFFICIENT_INVENTORY'); let cart = db.carts.find(x => x.userId === user.id); if (!cart) { cart = { id: id(), userId: user.id, updatedAt: now() }; db.carts.push(cart); } let item = db.cartItems.find(x => x.cartId === cart.id && x.productId === product.id); if (item) item.quantity = d.quantity; else { item = { id: id(), cartId: cart.id, productId: product.id, quantity: d.quantity }; db.cartItems.push(item); } cart.updatedAt = now(); save(); return respond(res, 200, { cart: cartView(user.id) }); }
    if (method === 'PATCH' && /^\/api\/cart\/items\/[^/]+$/.test(path)) { const user = auth(req); const d = await body(req); const item = db.cartItems.find(x => x.id === path.split('/').pop()); const cart = item && db.carts.find(x => x.id === item.cartId); if (!item || !cart || cart.userId !== user.id) fail(404, 'Cart item not found', 'NOT_FOUND'); if (!Number.isInteger(d.quantity) || d.quantity < 1 || d.quantity > 99) fail(422, 'quantity must be an integer from 1 to 99', 'VALIDATION_ERROR'); const stock = db.inventory.find(x => x.productId === item.productId).quantity; if (d.quantity > stock) fail(409, 'Insufficient inventory', 'INSUFFICIENT_INVENTORY'); item.quantity = d.quantity; cart.updatedAt = now(); save(); return respond(res, 200, { cart: cartView(user.id) }); }
    if (method === 'DELETE' && /^\/api\/cart\/items\/[^/]+$/.test(path)) { const user = auth(req); const item = db.cartItems.find(x => x.id === path.split('/').pop()); const cart = item && db.carts.find(x => x.id === item.cartId); if (!item || !cart || cart.userId !== user.id) fail(404, 'Cart item not found', 'NOT_FOUND'); db.cartItems = db.cartItems.filter(x => x.id !== item.id); save(); return respond(res, 200, { cart: cartView(user.id) }); }
    if (method === 'POST' && path === '/api/checkout') { const user = auth(req); const key = req.headers['idempotency-key']; if (!key || key.length < 8 || key.length > 200) fail(422, 'A valid Idempotency-Key header is required', 'VALIDATION_ERROR'); const existing = db.orders.find(x => x.userId === user.id && x.idempotencyKey === key); if (existing) return respond(res, 200, { order: orderView(existing), idempotent: true }); const d = await body(req); const shippingAddress = d.shippingAddressId ? db.addresses.find(x => x.id === d.shippingAddressId && x.userId === user.id) : null; if (!shippingAddress) fail(422, 'A shipping address you own is required', 'VALIDATION_ERROR'); if (d.paymentToken === 'decline') fail(402, 'Payment was declined', 'PAYMENT_DECLINED'); const cart = cartView(user.id); if (!cart.items.length) fail(422, 'Cart is empty', 'EMPTY_CART'); for (const line of cart.items) if (line.quantity > line.product.inventory) fail(409, `${line.product.name} is no longer available`, 'INSUFFICIENT_INVENTORY'); const shippingCents = cart.subtotalCents >= 5000 ? 0 : 699; const order = { id: id(), userId: user.id, addressSnapshot: shippingAddress, subtotalCents: cart.subtotalCents, shippingCents, totalCents: cart.subtotalCents + shippingCents, status: 'paid', idempotencyKey: key, createdAt: now() }; db.orders.push(order); for (const line of cart.items) { const inv = db.inventory.find(x => x.productId === line.product.id); inv.quantity -= line.quantity; inv.updatedAt = now(); db.orderItems.push({ id: id(), orderId: order.id, productId: line.product.id, productName: line.product.name, unitPriceCents: line.product.priceCents, quantity: line.quantity }); } db.payments.push({ id: id(), orderId: order.id, provider: 'test', providerReference: `pay_${randomBytes(8).toString('hex')}`, amountCents: order.totalCents, status: 'succeeded', createdAt: now() }); const rawCart = db.carts.find(x => x.userId === user.id); db.cartItems = db.cartItems.filter(x => x.cartId !== rawCart?.id); save(); return respond(res, 201, { order: orderView(order), idempotent: false }); }
    if (method === 'GET' && path === '/api/orders') { const user = auth(req); return respond(res, 200, { orders: db.orders.filter(x => x.userId === user.id).map(orderView) }); }
    if (method === 'GET' && /^\/api\/orders\/[^/]+$/.test(path)) { const user = auth(req); const order = db.orders.find(x => x.id === path.split('/').pop()); if (!order || (order.userId !== user.id && user.role !== 'admin')) fail(404, 'Order not found', 'NOT_FOUND'); return respond(res, 200, { order: orderView(order) }); }
    if (method === 'POST' && path === '/api/admin/categories') { auth(req, true); const d = await body(req); const name = validString(d.name, 'name', 2, 80); const slug = slugify(d.slug || name); if (!slug || db.categories.some(x => x.slug === slug)) fail(409, 'Category slug already exists', 'CONFLICT'); const category = { id: id(), name, slug }; db.categories.push(category); save(); return respond(res, 201, { category }); }
    if (method === 'POST' && path === '/api/admin/products') { auth(req, true); const d = await body(req); const name = validString(d.name, 'name', 2, 160); if (!money(d.priceCents) || !Number.isInteger(d.inventory) || d.inventory < 0) fail(422, 'priceCents and inventory must be non-negative integers', 'VALIDATION_ERROR'); if (!db.categories.some(x => x.id === d.categoryId)) fail(422, 'categoryId is invalid', 'VALIDATION_ERROR'); const slug = slugify(d.slug || name); if (db.products.some(x => x.slug === slug)) fail(409, 'Product slug already exists', 'CONFLICT'); const product = { id: id(), categoryId: d.categoryId, name, slug, description: validString(d.description, 'description', 1, 2000), priceCents: d.priceCents, active: d.active !== false, createdAt: now() }; db.products.push(product); db.inventory.push({ productId: product.id, quantity: d.inventory, updatedAt: now() }); save(); return respond(res, 201, { product: productView(product) }); }
    if (method === 'PATCH' && /^\/api\/admin\/products\/[^/]+$/.test(path)) { auth(req, true); const product = db.products.find(x => x.id === path.split('/').pop()); if (!product) fail(404, 'Product not found', 'NOT_FOUND'); const d = await body(req); if (d.name !== undefined) product.name = validString(d.name, 'name', 2, 160); if (d.description !== undefined) product.description = validString(d.description, 'description', 1, 2000); if (d.priceCents !== undefined) { if (!money(d.priceCents)) fail(422, 'priceCents must be a non-negative integer', 'VALIDATION_ERROR'); product.priceCents = d.priceCents; } if (d.active !== undefined) { if (typeof d.active !== 'boolean') fail(422, 'active must be boolean', 'VALIDATION_ERROR'); product.active = d.active; } if (d.inventory !== undefined) { if (!Number.isInteger(d.inventory) || d.inventory < 0) fail(422, 'inventory must be a non-negative integer', 'VALIDATION_ERROR'); const inv = db.inventory.find(x => x.productId === product.id); inv.quantity = d.inventory; inv.updatedAt = now(); } save(); return respond(res, 200, { product: productView(product) }); }
    fail(404, 'Route not found', 'NOT_FOUND');
  } catch (error) { respond(res, error.status || 500, { error: { code: error.code || 'INTERNAL_ERROR', message: error.status ? error.message : 'Unexpected server error' } }); }
}

if (require.main === module) http.createServer(handler).listen(PORT, () => console.log(`Ecommerce API listening on http://localhost:${PORT}`));
module.exports = { handler };
